server:
  port: 8888

spring:
  application:
    name: cloud-wxpay-service

  ########################################################
  ### 运行环境配置
  ########################################################
  #运行环境 1.开发环境 2.测试环境 3.生产环境 一定要记得改环境
gwkj.nc.env: 2

